export const cardsData = [
  { name: "Rahul Sharma", bookmarked: false, id: 0 },
  { name: "Amit Pandey", bookmarked: true, id: 1 },
  { name: "Joy Banerjee", bookmarked: false, id: 2 },
  { name: "Nishant Ghosh", bookmarked: false, id: 3 },
  { name: "Narendra Modi", bookmarked: true, id: 4 },
  { name: "Mamta Banerjee", bookmarked: true, id: 5 },
  { name: "Yugender G.", bookmarked: false, id: 6 },
  { name: "Manish Singh", bookmarked: true, id: 7 },
  { name: "Abhay Bhati", bookmarked: true, id: 8 },
  { name: "Amit Shah", bookmarked: false, id: 9 },
  { name: "Yogi Aditynaath", bookmarked: true, id: 10 },
  { name: "Om Kumar", bookmarked: false, id: 11 },
  { name: "Ram Jhunjhunwala", bookmarked: true, id: 12 },
];
